sudo: required
language: java
os: linux
jdk:
 - oraclejdk8
services:
 - docker
before_install:
 - chmod +x mvnw
install:
 - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
 - mkdir -p .bin; mv ./kubectl .bin/kubectl && chmod +x .bin/kubectl
 - export PATH="$TRAVIS_BUILD_DIR/.bin:$PATH"
 - wget https://cdn.rawgit.com/Mirantis/kubeadm-dind-cluster/master/fixed/dind-cluster-v1.7.sh && chmod +x dind-cluster-v1.7.sh && ./dind-cluster-v1.7.sh up
 - export PATH="$HOME/.kubeadm-dind-cluster:$PATH"

script:
 - ./mvnw clean install -B
 - kubectl get nodes
 - kubectl create -f https://raw.githubusercontent.com/kubernetes/kubernetes/master/examples/storage/redis/redis-controller.yaml
 - kubectl get rc
 - kubectl get pods
after_success:
 - docker login -u $DOCKER_USER -p $DOCKER_PASS
 - export IMAGE_NAME=bochwafa/backendspringboot
 - docker build -t $IMAGE_NAME .
 - docker tag $IMAGE_NAME $IMAGE_NAME:$TAG
 - docker push $IMAGE_NAME
deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: backendalltogether